services:
  api:
    container_name: card-scanner.api
    ports:
      - "7001:3000"
    depends_on:
      - pg
    networks:
      - default
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

  pg:
    container_name: card-scanner.pg
    ports:
      - "7000:5432"
    networks:
      - default
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  default:
    name: card-scanner-network
    driver: bridge
    external: true
